// TypeScript Type Definitions for ts-native Plugin
// Auto-generated by tsnp for crate 'metric-api'
//
// This file provides TypeScript type definitions for Rust FFI functions.
// Import this module in your TypeScript code to get type safety and IDE autocomplete.
//
// Usage:
//   import { functionName } from "tsnp-metric-api";

declare module "tsnp-metric-api" {
}
